version: "3"

volumes:
  db-data:
    external: false
  redis-data:
    external: false

services:
  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    image: postgres:9.5
    volumes:
      - db-data:/user/local/pgsql/data
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis-data:/data

  web:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
      - sidekiq
    ports:
      - "3000:3000"
    env_file:
      - .env
    tty: true
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
